### ISSUE TITLE
I paid $14 to become a sponsor why can't I see this source code?

### ISSUE THREAD

**Issue by Radnez** [JohannesMilke/firebase_auth_email#1]

**Comment by Radnez** [comment]
<img width="532" alt="Screenshot 2023-04-07 at 12 00 28" src="https://user-images.githubusercontent.com/48943658/230589651-fb683704-eeb1-4da3-ad79-6883d6df23ea.png">

**Comment by JohannesMilke** [comment]
@Radnez You have already access to all source codes: https://github.com/orgs/JohannesMilke-Sponsors/repositories
